# 開発用
# version: "3.8"

# services:
#   app:
#     build: .
#     ports:
#       - "4000:3000"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     env_file:
#       - .env.local


# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
# 本番モードで起動する用
version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:3000"
    env_file:
      - .env.local
