// 全体のレイアウトを定義するファイル

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { ThemeToggle } from "@/components/ThemeToggle";
import { cookies } from "next/headers";
import { Github } from "lucide-react";
import { ScrollToTopButton } from "@/components/ScrollToTopButton";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore =await  cookies();
  const theme = cookieStore.get("theme")?.value ?? "light";

  return (
    <html lang="ja" className={theme === "dark" ? "dark" : ""}>
      <body className="antialiased">

        <header className="sticky top-0 z-40 backdrop-blur-sm bg-white/60 dark:bg-neutral-900/60 border-b border-gray-200 dark:border-white/10 shadow-sm">
          <div className="w-full px-4 py-3 flex items-center justify-between">

            {/* 左：ロゴ＋タイトル */}
            <div className="flex items-center gap-2 text-gray-700 dark:text-gray-100">
              <Github className="w-5 h-5" />
              <span className="text-lg font-semibold tracking-tight">GitHub Explorer</span>
            </div>

            {/* 右：テーマ切り替え */}
            <ThemeToggle />
          </div>
        </header>

        {children}
        <ScrollToTopButton /> 
      </body>
    </html>
  );
}
